- apt_repository: repo='deb http://apt.datadoghq.com/ stable main' state=present
- apt_key: keyserver=keyserver.ubuntu.com id=C7A7DA52
- apt: name=datadog-agent update_cache=yes
- service: name=datadog-agent enabled=true
